[tool.poetry]
name = "online-shop"
version = "0.1.0"
description = ""
authors = ["Valentyn Malenchak <valentyn17@gmail.com>"]
readme = "README.md"
packages = [{include = "online_shop"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.1"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
pytest = "^7.4.0"
poetry = "^1.5.1"
httpx = "^0.24.1"
invoke = "^2.2.0"
mypy = "^1.4.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.0.281"
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
