# Enable the pycodestyle (`E`), Pyflakes (`F`), pycodestyle warnings (`W`),
# isort (`I`), pep8-naming (`N`), Pylint (`PL`) and McCabe complexity (`C901`).
select = ["E", "F", "W", "I", "N", "PL", "C90"]

# Allow autofix for isort and F401 imported but unused.
fixable = ["I", "F401"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88

# Assume Python 3.10.
target-version = "py310"